# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Run a dev
        run: echo "key ${{ secrets.KEY }}"
  build-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Run a prod
        run: |
          echo "key ${{ secrets.KEY }}"
          echo "env ${{ secrets.ENV }}"
        
